# Generated by Django 2.0.7 on 2018-10-05 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'canal',
                'verbose_name_plural': 'canais',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.Canal', verbose_name='canal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
