# Generated by Django 2.0.7 on 2018-10-05 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_canal_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='mensagempv')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagemrecipient', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagemsender', to=settings.AUTH_USER_MODEL, verbose_name='remetente')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name': 'mensagem', 'verbose_name_plural': 'mensagens'},
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='message',
            field=models.TextField(verbose_name='mensagens'),
        ),
    ]
