# Generated by Django 2.0.7 on 2018-10-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensagempv_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='mensagempv',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagem'),
        ),
    ]
